[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_INSTALL_CMD = "cd server && pip install -r requirements.txt"
